header:
    title: WAI
    #text: Women in Artificial Intelligence
    button: Learn More About Us
    buttonlink: "#services" # "#{section}" or "URL/page link"

services:
    title: "about us"
    text: >
      We are a club of MIT and Harvard students who are interested in artificial intelligence and machine learning. Beginners and interested individuals with any level of knowledge are welcome!
      
      We use an inclusive definition of the word women, and the purpose of the Women in Artificial Intelligence group is to provide a supportive community for cisgender women, transgender women, genderqueer women and individuals, and non-binary individuals pursuing studies or research in AI and machine learning at MIT and Harvard.

      We are structured formally as a reading group, meeting every other week to discuss papers of interest related to artificial intelligence and machine learning. Additionally, we endeavor to serve as an organizing body to get more women involved in AI and ML, working with MIT and Harvard faculty to host more female speakers for machine intelligence-related seminars.
    
    section: services
    list:
      - title: "Accessibility"
        desc: "Make machine learning and artificial intelligence more accessible, especially for those who are underrepresented in the field."
        icon: fas fa-door-open #find more at https://fontawesome.com/icons
      - title: "Support"
        desc: "Create an environment safe from judgment, hostility, and competition."
        icon: fas fa-people-carry
      - title: "Education"
        desc: "Learn more about ML and AI ourselves as well as educate others, especially beginners, by providing helpful resources and role models in the field."
        icon: fas fa-laptop       

portfolio:
    title: "expert interview series"
    text: "interviews with outstanding women experts in the field."
    section: portfolio

portfolioyoung:
    title: "young scientists interview series"
    text: "interviews with outstanding young women scientists and engineers."
    section: portfolioyoung
    

timeline:
    title: "resources" 
    text: "a collection of our favorite resources."
    section: timeline
    events:
      - title: "Courses"
        desc: "
        Andrew Ng Deep Learning Videos: [Youtube](https://www.youtube.com/watch?v=PPLop4L2eGk&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN).<br>

        Intro ML at MIT: [MIT Open Course Ware](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-867-machine-learning-fall-2006/).<br>

        Intro AI at MIT: [MIT Open Course Ware](https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/) and [Youtube](https://www.youtube.com/watch?v=TjZBTDzGeGg&list=PLUl4u3cNGP63gFHB6xb-kVBiQHYe_4hSi).<br>

        Deep Learning Monthlong Course: [Youtube](https://www.youtube.com/watch?v=njKP3FqW3Sk)."
        
        image: "/assets/img/resources/online_course.jpg"
        align: left
      - title: "Math for Machine Learning"
        desc: "
        Technical videos from Mathematical Monk about ML: [Youtube](https://www.youtube.com/watch?v=yDLKJtOVx5c).<br>
        
        Learn linear algebra with [3blue1brown on Youtube](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).<br>
        
        Learn matrix methods with [MIT's Gil Strang](https://www.youtube.com/watch?v=Cx5Z-OslNWE&list=PLUl4u3cNGP63oMNUHXqIUcrkS2PivhN3k).<br>
 
        Learn basic probability with [Mr. Nystrom](https://www.youtube.com/watch?v=dqgZxu9qc2w&list=PLFGZup_HuWTtIs0Xbzt7vDoFrnZxN4VXT).<br>

        Learn advanced probability with [Mathematical Monk](https://www.youtube.com/playlist?list=PL17567A1A3F5DB5E4)."
        
        image: "/assets/img/resources/math.jpg"
        align: right
      - title: "Other Resources"
        desc: "
        Deep Learning by Goodfellow et al: free book available at [deeplearningbook.org](https://www.deeplearningbook.org).<br>
        
        Practice data science problems on [Kaggle](https://www.kaggle.com).<br>
  
        Read ML-related articles on [Distill](https://distill.pub)."

        image: "/assets/img/resources/book.jpg"     
    end: "Tell us your favorite resources!"

team:
    title: "members"
    text: "meet our leadership and other amazing members!"
    section: team
    people:
      - name: "Katie Collins"
        role: "Co-President and Founder, she/her/hers"
        image: assets/img/team/katie_c.png
      - name: "Megan Wei"
        role: "Co-President and Chief Financial Officer, she/her/hers"
        image: assets/img/team/megan_w.png
      - name: "Jacqueline Valeri"
        role: "Co-President and Chief Technology Officer, she/her/hers"
        image: assets/img/team/jackie_v.png
      - name: "Gaby Ecanow"
        role: "Director of Professional Development, she/her/hers"
        image: assets/img/team/gaby_e.jpg
      - name: "Michelle Li"
        role: "Mentorship Program Lead, she/her/hers"
        image: assets/img/team/michelle_l.jpeg
      - name: "Neha Hulkund"
        role: "Treasurer, she/her/hers"
        image: assets/img/team/neha_h.jpg
      - name: "Zad Chin"
        role: "Education Committee Lead, she/her/hers"
        image: assets/img/team/zad_c.jpg
      - name: "Nina Rhone"
        role: "Director of Marketing and Design, she/her/hers"
        image: assets/img/team/nina_r.jpeg
      - name: "Lindsey McAllister"
        role: "Graphic Design Lead"
        image: assets/img/team/koala_icon.png
      - name: "Shelley Choi"
        role: "Co-Director of Young Scientists Interview Series, she/her/hers"
        image: assets/img/team/shelley_c.png
      - name: "Sharon Jiang"
        role: "Co-Director of Young Scientists Interview Series, she/her/hers"
        image: assets/img/team/koala_icon.png
      - name: "Alisa Hathaway"
        role: "Co-Director of Expert Interview Series, she/her/hers"
        image: assets/img/team/alisa_h.jpg
      - name: "Cindy Zhang"
        role: "Director of Video Editing, she/her/hers"
        image: assets/img/team/cindy_z.jpg
      - name: "Fatima Gunter-Rahman"
        role: "she/her/hers"
        image: assets/img/team/fatima_g.jpg
      - name: "Zana Bucinca"
        role: "she/her/hers"
        image: assets/img/team/zana_b.jpg
      - name: "Jenny Cai"
        role: "she/her/hers"
        image: assets/img/team/jenny_c.jpeg
      - name: "Joli Dou"
        role: "she/her/hers"
        image: assets/img/team/joli_d.jpg
      - name: "Caroline Cunningham"
        role: "she/her/hers"
        image: assets/img/team/caroline_c.jpg
      - name: "Alison Wang"
        role: "she/her/hers"
        image: assets/img/team/koala_icon.png
      - name: "Helen Yang"
        role: "she/her/hers"
        image: assets/img/team/helen_y.jpg
      - name: "Subha Nawer Pushpita" 
        role: "she/her/hers"
        image: assets/img/team/subha_p.jpg
      - name: "Shinjini Ghosh"
        image: assets/img/team/shinjini_g.jpg
      - name: "Jennifer Hu"
        role: "she/her/hers"
        image: assets/img/team/jennifer_h.jpg
      - name: "Carina Kauf"
        role: "she/her/hers"
        image: assets/img/team/carina_k.jpg
      - name: "Claire Lu"
        role: "she/her/hers"
        image: assets/img/team/claire_l.jpg
      - name: "Emily Alsentzer"
        role: "she/her/hers"
        image: assets/img/team/emily_a.jpeg
      - name: "Vivienne Zhang"
        image: assets/img/team/vivienne_z.jpg
      - name: "Jimin Lee"
        role: "she/her/hers"
        image: assets/img/team/jimin_l.png
      - name: "Adrianna Wojtyna"
        role: "she/her/hers"
        image: assets/img/team/adrianna_w.jpg
      - name: "Sandra Romero Pinto"
        role: "she/her/hers"
        image: assets/img/team/sandra_r.jpg
      - name: "Anna G. Green"
        role: "she/her/hers"
        image: assets/img/team/anna_g.jpg
      - name: "Vicky Zheng"
        role: "she/her/hers"
        image: assets/img/team/vicky_z.jpg
      - name: "Fiona Millan"
        role: "she/her/hers"
        image: assets/img/team/koala_icon.png  
      - name: "Selena Zhang"
        role: "she/her/hers"
        image: assets/img/team/selena_z.jpg
      - name: "Jessica Boye-Doe"
        role: "she/her/hers"
        image: assets/img/team/jessica_b.JPG
      - name: "Helen Propson"
        role: "she/her/hers"
        image: assets/img/team/helen_p.JPG
      - name: "Sarah Wei"
        role: "she/her/hers"
        image: assets/img/team/sarah_w.jpg
      - name: "Sara Modiano"
        role: "she/her/hers"
        image: assets/img/team/sara_m.jpeg
      - name: "Yongxin (Emily) Shi"
        role: "she/her/hers"
        image: assets/img/team/yongxin_s.jpg
      - name: "Maegan Jong"
        role: "she/her/hers"
        image: assets/img/team/maegan_j.jpeg
      - name: "Anusha Puri"
        role: "she/her/hers"
        image: assets/img/team/anusha_p.jpg
      - name: "Yao Yin"
        role: "she/her/hers"
        image: assets/img/team/yao_y.jpg
      - name: "Kayla Huang"
        role: "she/her/hers"
        image: assets/img/team/kayla_h.jpg
      - name: "Noa Korneev"
        role: "she/her/hers"
        image: assets/img/team/noa_k.jpg
      - name: "Eshika Saxena"
        role: "she/her/hers"
        image: assets/img/team/eshika_s.jpg
      - name: "Mari Kikuta"
        role: "she/her/hers"
        image: assets/img/team/koala_icon.png
      - name: "Elizabeth Bondi"
        role: "she/her/hers"
        image: assets/img/team/elizabeth_b.jpg
      - name: "Cindy Liu"
        role: "she/her/hers"
        image: assets/img/team/cindy_l.jpeg
      - name: "Elizabeth Lee"
        role: "she/her/hers"
        image: assets/img/team/koala_icon.png
      - name: "Agi Kajanaku"
        image: assets/img/team/agi_k.jpg
      - name: "Kate Pearce"
        image: assets/img/team/kate_p.jpg
      - name: "Summer Vo"
        role: "she/her/hers"
        image: assets/img/team/koala_icon.png
      - name: "Diana Faust"
        image: assets/img/team/koala_icon.png
      - name: "Kat Wicks"
        image: assets/img/team/koala_icon.png

footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"  
      - url: https://github.com/mitharvardwai
        icon: "fab fa-github"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
